GRANT SELECT, INSERT, DELETE, UPDATE ON Users TO UserManager;
GRANT SELECT, INSERT, DELETE, UPDATE ON UserGroup TO GroupManager;
GRANT SELECT, INSERT, DELETE, UPDATE ON UserGroup TO ConnectManager;
GRANT SELECT, INSERT, DELETE, UPDATE ON Menu TO GroupManager;
GRANT SELECT ON UserMenu TO UserManager;
GRANT SELECT ON UserMenu TO GroupManager;
GRANT SELECT ON UserMenu TO ConnectManager;
GRANT INSERT, DELETE ON UserMenu TO GroupManager;

